name: cskills
description: A quiz app help study C-skills.

publish_to: 'none'

version: 1.2.0+1

environment:
  sdk: ">=2.9.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  page_transition: ^2.0.2
  animated_text_kit: ^4.2.1
  circular_countdown_timer: ^0.2.0
  animated_splash_screen: ^1.1.0-nullsafety.0
  flutter_launcher_icons: ^0.8.1
  flutter_screenutil: ^5.0.0+2
  showcaseview: ^1.1.1
  shared_preferences: ^0.5.12+4
  share: ^2.0.4
  fluttertoast: ^8.0.8
  audioplayers: ^0.16.0
  advance_pdf_viewer: ^1.0.0
  url_launcher: ^6.0.5
  flutter_automation: ^1.2.2

flutter_icons:
  ios: true
  android: true
  image_path: "icons/exam.png"

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/sounds/
    - assets/files/
    - icons/
  
  fonts:
    - family: AkayaKanadaka
      fonts:
      - asset: fonts/AkayaKanadaka-Regular.ttf